name: Deploy Project
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      js-filename: ${{ steps.publish-js-filename.outputs.js-filename }}
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Publish JS filename
        id: publish-js-filename
        run: find dist/assets/*.js -type f -execdir echo 'js-filename={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: Output files
        run: ls
      - name: Output JS filename
        run: echo ${{ needs.build.outputs.js-filename }}
      - name: Deploy to Server
        run: echo "Deploying to server..."
